name: Build macOS App

on:
  workflow_dispatch:   # lets you run it manually
  push:
    branches: [ master ] # also runs on pushes to main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile main.py

      - name: Upload macOS Binary
        uses: actions/upload-artifact@v3
        with:
          name: macos-binary
          path: dist/*
